#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Ben
# SPDX-License-Identifier: GPL-3.0-only

import sys

ans = 0
for line in sys.stdin;
    try:
        ans += int(line)
    except:
        ans += float(line)
print(ans)
